config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get "kidsBikes" => "pages#kidsBikes"
  get "pedestrians" => "pages#pedestrians"
  get "road_rules" => "pages#road_rules"
  get "road_safety_games" => "pages#road_safety_games"
  get "skateboards_n_scooters" => "pages#skateboards_n_scooters"
  
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def kidsBikes
  end

  def pedestrians
  end

  def roads_rules
  end

  def road_safety_rules
  end

  def skateboards_n_scooters
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<!-- Wrap all page content here -->
<div class="navbar-wrapper">
  <div class="container">
    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="fa fa-google-wallet navbar-brand"><b><i> Welcome to Stephanie's road safety application</i></b> !</a>
        </div>
        
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to root_path do %>
                <span class="glyphicon glyphicon-home"></span> Home
              <% end %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-duplicate"></span> Dropdown<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Kids bike rules n tips", kidsBikes_path %></li>
                <li><%= link_to "Skateboards n scooters", skateboards_n_scooters_path %></li>
                <li><%= link_to "Pedestrians", pedestrians_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Road safety games", road_safety_games_path %></li>
              </ul>
            </li>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<%= favicon_link_tag("lights.png", alt: " ashleigh wilson MyCV") %>
	  <title>AnniesRoadSafety</title>
	  <!--[if lt IE 9]>
	      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
	    <![endif]-->
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <link href='http://fonts.googleapis.com/css?family=Playfair+Display' rel='stylesheet' type='text/css'>
	  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
	  <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<%= render 'layouts/header' %>

		<%= yield %>
	</body>
</html>

app/views/pages/home.html.erb
<div id="primary-content">
	<div class="container-pages-home">
		<h1 class="orange">Childish - Ways </h1>
		<div id="flip-element">
			<h2 class="title-name">What happens when it all goes wrong ?</h2>
		</div>
		<hr class="featurette-divider">
		<div id="bounce-right">
			<p class="lead">Click play below to find out..</p>
		</div>
		
		<div id="zoom-content">
			<iframe width="95%" height="470" src="https://www.youtube.com/embed/ddTlNEWFIxc?rel=0" frameborder="0" allowfullscreen></iframe>
		</div>
		
		<div id="bounceleft-content">
			<h4>Now let me teach you how to stay alive on our roads</h4>
			<p><i class="orange">go to the dropdown above</i></p>
		</div>	
		<hr class="featurette-divider">
	</div>
</div>

app/views/pages/kidsBikes.html.erb
<div id="primary-content">
	<div class="container-pages">
		
		<div id="flip-element">
			<h1>Kids bike | skills n rules</h1>
		</div>
		
		<div id="bounce-content">
			<div class="slow-content">
				<hr class="featurette-divider">

				<div class="row skills">
  				<div class="col-md-4 top">
  					<div class="container-images">
  						<img src="http://childsafetyblog.org/wp-content/uploads/2014/07/Bike-photo-July-2014.jpg" class="img-responsive" alt="bike skills">
  					</div>
  				</div>
			
  				<div class="col-md-8"><h3 class="green">Be Seen Be Safe !</h3>
  					<p class="beta-p left">Wear high visibility or brightly coloured clothing and use lights. </p> 
						<p class="beta-p left">If you ride your bike in poor lighting conditions or at night wear a reflective vest.</p>
						<p class="beta-p left">Be safe be seen when you are on the road riding your bike.</p>
						<p class="beta-p left">Be cool and wear your helmet it could save your life if your in a accident and it just looks silly when you see someone riding a bike without one.</p>
					</div>
				</div>

				<div class="row skills">
  				<div class="container-images-rgt">
  					<span>
  						<img src="http://www.nzta.govt.nz/resources/roadcode/cyclist-code/gfx/car-door-zone.jpg" class="img-responsive" alt="cycle skills">
  					</span>
  				</div>
  				<div class="col-md-8"><h3 class="orange">Be Aware !</h3>
  					<span class="e-text">
  						<p class="beta-p left">Watch for car doors opening, potholes, rubbish, grates, and pedestrians. Always check for left turning vehicles.</p> 
							<p class="beta-p left">Sometimes others on the road may not see you no matter what your wearing always remember it's your job to keep an eye out for the unexpected, here's a tip - when the traffic light's turn green still check your left and right to make sure the road is clear.</p>
							<p class="beta-p left">Be carefull to watch out for animals they can run out onto the road at any time and may make you have a crash.</p>
						</span>
  				</div>
				</div>

				<div class="row skills">
					<div class="col-md-4 top">
  					<div class="container-images">
  						<img src="http://cycleleeds.org.uk/assets/img/school-cycle-training.jpg" class="img-responsive" alt="Bike skills">
  					</div>
					</div>
  				<div class="col-md-8"><h3 class="green">Predictable and Confident !</h3>
  					<p class="beta-p left">Make eye contact with other road users. Maintain a straight line and don’t pass on the left hand side.</p>
						<p class="beta-p left">Use hand signals and a bell. Ride at least one metre from parked cars. Use the cycle or traffic lane.</p>
						<p class="beta-p left">Always make your intentions clear to other road users. Using simbolic gestures like when turning a corner or stopping is the key here and just using your common sense is where it's at.</p>
  				</div>
				</div>
		
				<div class="row skills top">
					<div class="container-images-rgt">
						<span>
							<img src="http://www.nzta.govt.nz/resources/roadcode/gfx/roadcode-cyclists-cover.jpg" class="img-responsive" alt="cycle rules nz">
						</span>
					</div>
					<div class="col-md-8 adm"><h3 class="orange">Find Resources</h3>
						<span class="e-text">
							<p class="beta-p left">You can find out lot's of other info on 'cycling right' here at the<a href="http://www.nzta.govt.nz/resources/roadcode/cyclist-code/about-cycling/rules.html" target="_blank"><i> NZTA</i></a>  just click the link to check it out.</p>
   						<p class="beta-p left"></p>
   						<p class="beta-p left">Here's another tip, When cycling behind other cyclists and vehicles you must be able to stop, keeping clear of the vehicle in front, if it stops suddenly. It is recommended you keep at least two seconds behind..</p>
   						<p class="beta-p left">If you can get a copie of the new Zealand road code and read it ! you will be a better cyclist and become more confident when you know the road rules. Be safe and have fun riding your bike.</p>
   					</span>
   				</div>
				</div>
				<hr class="featurette-divider">
			</div>
		</div>
	</div>
</div>

app/views/pages/pedestrians.html.erb
<div id="primary-content">
	<div class="container-pages">
		
		<div id="flip-element">
			<h1>Information for pedestrians</h1>
		</div>
		
		<div id="bounce-content">
			<div class="slow-content">
				<hr class="featurette-divider">

				<div class="row skills">
  				<div class="col-md-4 top">
  					<div class="container-images">
  						<img src="http://www.sha.maryland.gov/OOTSImages/talesoftheroad.png" class="img-responsive" alt="pedestrian skills">
  					</div>
  				</div>
			
  				<div class="col-md-8"><h3 class="green">Think about it</h3>
  					<p class="beta-p left">As a pedestrian, it's important that you follow the road rules and guidelines shown below. They will help ensure your safety when you're walking near roads or crossing the road.</p> 
					</div>
				</div>

				<div class="row skills">
  				<div class="container-images-rgt">
  					<span>
  						<img src="http://www.unitypoint.org/blankchildrens/filesimages/Kids%20walking%20to%20school.jpg" class="img-responsive" alt="pedestrian skills">
  					</span>
  				</div>
  				<div class="col-md-8"><h3 class="orange"> Some general pedestrian guidelines</h3>
  					<span class="e-text">
  						<p class="beta-p left">Footpaths provide a safe place for you to walk. Where a footpath is provided, use it.</p> 
							<p class="beta-p left">When using a shared path you must be careful and considerate. A shared path may be a cycle path, a footpath, or some other kind of path used by pedestrians, cyclists, riders of mobility devices and riders of wheeled recreational vehicles at the same time. There will be a sign telling you it is a shared path.</p>
							<p class="beta-p left">Be careful when crossing driveways, particularly when your visibility is restricted by buildings or fences. Remember, if a driver is coming out of a driveway, their vision will be restricted and they may not see you.</p>
						</span>
  				</div>
				</div>

				<div class="row skills">
					<div class="col-md-4 top">
  					<div class="container-images">
  						<img src="http://static2.stuff.co.nz/1233108507/462/522462.jpg" class="img-responsive" alt="pedestrian skills">
  					</div>
					</div>
  				<div class="col-md-8"><h3 class="green">School & Pedestrian crossings</h3>
  					<p class="beta-p left">If you are within 20 metres of a pedestrian crossing, footbridge, underpass or traffic signals, you must use it to cross the road.</p>
						<p class="beta-p left">Don't dawdle on a pedestrian crossing.</p>
						<p class="beta-p left">Don't step out suddenly onto a pedestrian crossing if any vehicles are so close to the crossing that they cannot stop.</p>
  				</div>
				</div>
		
				<div class="row skills top">
					<div class="container-images-rgt">
						<span>
							<img src="http://www.nzta.govt.nz/resources/nz-pedestrian-profile/img/nz-pedestrian-profile-cover.jpg" class="img-responsive" alt="pedestrian rules nz">
						</span>
					</div>
					<div class="col-md-8 adm"><h3 class="orange">Resources</h3>
						<span class="e-text">
							<p class="beta-p left">You can find out lot's of other info on 'pedestrians' at the<a href="http://www.nzta.govt.nz/resources/roadcode/about-other-road-users/information-for-pedestrians.html" target="_blank"><i> NZTA</i></a>  just click the link to check the info.</p>
   						<p class="beta-p left"></p>
   						<p class="beta-p left">Here's another tip, remember, it takes time for a vehicle to stop. Be sensible and wait for a gap in the traffic before crossing the road.</p>
   						<p class="beta-p left">If you can get a copie of the new Zealand road code and read it ! you will be a better pedestrian and become more confident when you know the road rules.</p>
   					</span>
   				</div>
				</div>
				<hr class="featurette-divider">
			</div>
		</div>
	</div>
</div>

app/views/pages/road_safety_games.html.erb
<div id="primary-content">
	<div class="container-pages-home">
		<div id="flip-element">
			<h1 class="orange">Awesome road safety games</h1>
		</div>
			<h2 class="title-name">Below are links to play online games for free, enjoy !</h2>
		<hr class="featurette-divider">
		<div id="bounce-right">
			<p class="lead">Click links to play..</p>
		</div>

		<div id="zoom-content">
			<p class="beta-p"><a href="http://talesoftheroad.direct.gov.uk/stop-look-listen.php" target="_blank"><i> Make me cross</i></a></p>
			<p class="beta-p"><a href="http://talesoftheroad.direct.gov.uk/be-bright.php" target="_blank"><i> Lighten Up</i></a></p>
			<p class="beta-p"><a href="http://talesoftheroad.direct.gov.uk/safer-place-to-cross.php" target="_blank"><i> Street Smarts</i></a></p>
			<p class="beta-p"><a href="http://talesoftheroad.direct.gov.uk/cycling-safety.php" target="_blank"><i> Fix n Ride</i></a></p>
		</div>
		
		<div id="bounceleft-content">
			<h4>Thank you for visiting my Road safety site i hope you learnt a bit about keeping your self safe ! </h4>
		</div>
		<div id="lightspeed2">	
			<p><i class="orange">Stephanie Rails. lol all rights not reserved ! 2015</i></p>
		</div>	
		<hr class="featurette-divider">
	</div>
</div>

app/views/pages/skateboards_n_scooters.html.erb
<div id="primary-content">
	<div class="container-pages">
		
		<div id="flip-element">
			<h1>Skateboards and Scooters</h1>
		</div>
		
		<div id="bounce-content">
			<div class="slow-content">
				<hr class="featurette-divider">

				<div class="row skills">
  				<div class="col-md-4 top">
  					<div class="container-images">
  						<img src="http://i.ytimg.com/vi/XqHO7aOHyN8/maxresdefault.jpg" class="img-responsive" alt="skates skills overview">
  					</div>
  				</div>
			
  				<div class="col-md-8"><h3 class="green">Safety Overview</h3>
  					<p class="beta-p left">When using in-line skates, a scooter or skateboard, are you a pedestrian? Or are you considered to be using a vehicle?  Generally, the answer is that you are considered to be a pedestrian, which determines where you can use your skates, scooters or skateboard. This section includes tips you can learn to help stay safe while on the move. </p>
					</div>
				</div>

				<div class="row skills">
  				<div class="container-images-rgt">
  					<span>
  						<img src="http://www.skateshop.ie/oldsite/images/2591667219_01ecace2cc.jpg" class="img-responsive" alt="skateboard skills">
  					</span>
  				</div>
  				<div class="col-md-8"><h3 class="orange">Where can you go ?</h3>
  					<span class="e-text">
  						<p class="beta-p left">Riding on the road is dangerous for any user so we strongly recommend using rollerblades, skates, scooters or skateboards on the footpath. An even better option is to use facilities such as skate parks – it’s much safer for everyone.</p> 
							<p class="beta-p left">However using your scoot skates and skateboard on the footpath is ok as long as you concider others and take care not to harm or endanger pedestrians.</p>
						</span>
  				</div>
				</div>

				<div class="row skills">
					<div class="col-md-4 top">
  					<div class="container-images">
  						<img src="http://cdni.wired.co.uk/620x413/s_v/scooter.jpg" class="img-responsive" alt="scoot skills">
  					</div>
					</div>
  				<div class="col-md-8"><h3 class="green">Being safe</h3>
  					<p class="beta-p left">Wear a helmet and safety gear such as wrist guards, elbow and knee pads, as well and closed shoes and brightly coloured clothing.</p>
						<p class="beta-p left">Practise riding skills away from traffic.</p>
						<p class="beta-p left">Always make your intentions clear to other pedestrians. Just using your common sense is where it's at.</p>
						<p class="beta-p left">See more about the<a href="http://www.nzta.govt.nz/vehicle/your/low-powered.html" target="_blank"><i> legal requirements for skateboards and scooters</i></a> .</p>
  				</div>
				</div>
				<hr class="featurette-divider">
			</div>
		</div>
	</div>
</div>